### ISSUE TITLE
Is interpolating expressions something that could be added?

### ISSUE THREAD

**Issue by KerfuffleV2** [Goncalerta/proc-quote#23]
From looking at the source, it doesn't seem like adding this would be extremely difficult, however I'm not sure if there's some subtle effect that actually would make this impossible.

I'm also not sure if you'd be adding features that diverge from the existing `quote!` macro.

I don't think this could be done in a way that is 100% compatible with `quote!`, but one approach would be to a separate macro that allows some extended features. Maybe something like `xquote!`

Here's an example use case: 
```rust
struct Blah { x: Ident, y: Ident }

impl ToTokens for Blah {
  fn to_tokens(&self, tokens: &mut TokenStream) {
    let x = self.x;
    let y = self.y;
    // Ignore that the actual generated code is nonsense, just an example.
    tokens.append_all(quote!( #x #y ))
  }
}
```

Instead of having to create a bunch of bindings before calling `quote!`:

```rust
struct Blah { x: Ident, y: Ident }

impl ToTokens for Blah {
  fn to_tokens(&self, tokens: &mut TokenStream) {
    tokens.append_all(xquote!( #$(self.x) #$(self.y) ))
  }
}
```
Another common case is having something that implements `IntoIterator` like an `Option`, but you have to create bindings with `let x = x.into_iter()` or to use an iterator multiple times it's necessary to do some something like:

```rust
let my_iter1 = blah.iter();
let my_iter2 = blah.iter();
quote!( #( #my_iter1 )* #( #my_iter2 )* )
```

Instead:

```rust
xquote!( #( #$( blah.iter() ) )* #( #$( blah.iter() ) )* )
```

Of course, it doesn't have to be `#$( ... )` for the expression interpolation syntax.

Anyway, if this isn't something you'd be opposed to on principle then I'd probably look into working on this and submitting a PR if I get it to a workable state.

**Comment by bluebear94** [comment]
This was suggested for `quote`, too, but [the author decided against adding it.](https://github.com/dtolnay/quote/pull/88#pullrequestreview-180577592)

**Comment by Goncalerta** [comment]
Yes, given that the original quote crate doesn't and will never support this, I also think that it won't be a good idea to add support in this crate, as that would promote a split ecosystem in the rust proc macros. I think that the transition between quote and proc-quote (and the other way around) should be as easy as possible, ideally just changing the crate name, and that is not possible if proc-quote starts supporting features that won't ever be implemented in the original quote crate.

That said, this doesn't mean I'm not open to other experimental ideas if there is potential interest in eventually implement then in the original quote crate.
