### ISSUE TITLE
Escape pound (#) with double-pound (##)

### ISSUE THREAD

**Issue by Goncalerta** [Goncalerta/proc-quote#8]
The example @siavash-hamedani gave in dtolnay/quote#99:

> ```rust
> let trait_name = ...
> quote! {
>     #[proc_macro_derive(#trait_name)]
>     ...
>     let derivee = ...
>     ...
>     quote!{
>         impl #trait_name for ## derivee {
>             ...
>         }
>     }
> }
> ```

**Comment by dtolnay** [comment]
FYI I don't think this would be a beneficial change. Some explanation in https://github.com/dtolnay/quote/pull/99#pullrequestreview-217013362.
